### PR TITLE
Use nccsv for example datasets for simplicity/visbility

### PR DESCRIPTION
**Pull request by srstsavage**
Using the text-based nccsv format allows us to the self describing/embedded metadata features of NetCDF while also allowing easy visibility and browsing of the source data (text is more accessible than binary files).

https://coastwatch.pfeg.noaa.gov/erddap/download/NCCSV.html

### CODE REVIEW

**Comment by MathewBiddle** [comment]
My concern with this is IOOS does link to these files as Gold Standard Example datasets for the IOOS Metadata Profile and I don't think we want to be recommending nccsv as the standard format.  https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#gold-standard-example-datasets

IMO we should be exemplifying how to load datasets from a variety of formats. So, I propose that we only change one of these netCDF files to nccsv, but leave the rest as nc. If it would be beneficial to the community, we can provide a .cdl next to the .nc for readability on GH.

**Comment by srstsavage** [comment]
@MathewBiddle That’s a valid concern. I hate violating DRY but what if we kept both nccsv and nc copies of the example datasets here, made the nc files the default, and included a script to generate the nc files from the nccsv files? That way we could use the nccsv files as the source of truth and cleanly track changes to them via git, but also demonstrate running ERDDAP with standard nc datasets.

**Comment by MathewBiddle** [comment]
That seems like a viable approach. I'm onboard with it, and interested in what the script would look like.

**Review by MathewBiddle — CHANGES_REQUESTED** [review]
Please add in the nccsv to nc script, if available.

**Comment by MathewBiddle** [comment]
@srstsavage FYI

The default branch has been renamed!
`master` is now named `main`

See https://github.com/ioos/erddap-gold-standard/issues/52

**Comment by srstsavage** [comment]
Closing in favor of the CDL approach in #70

**Pull request closed without merging**
