### PR TITLE
use erddap 2.23

### LINKED ISSUE #47: Update documentation to latest ERDDAP 2.23
The linked live demo runs ERDDAP 2.23, but the documentation and docker compose file are still on 2.18

I think this will require PRs to both master and gh-pages

### PR DESCRIPTION
**Pull request by callumrollo**
This partly resolves #47

### CODE REVIEW

**Review by ocefpaf — APPROVED** [review]
@MathewBiddle are you OK with these changes?

**Comment by MathewBiddle** [comment]
I don't recall the differences between 2.18 and 2.23. If there are changes to the information in datasets.xml or other configurations, we should update those as well. See https://erddap.github.io/changes.html for changes between 2.18 and 2.23.


Some notable ones: 
https://erddap.github.io/changes.html#changes2.21
> TO DO: For Java 17, you shouldn't use -d64 in JAVA_OPTS in setenv.bat or setenv.sh. So if it is there, please remove it. I think that 64 bit mode is now selected when you download a 64 bit version of Java. Thanks to Sam Woodman.

https://erddap.github.io/changes.html#changes2.19
> TO DO: Recommended: If your server's CPU has 4+ cores and 8+ GB of RAM, consider changing to these settings in your datasets.xml file:
```  
<nGridThreads>3</nGridThreads>
<nTableThreads>3</nTableThreads>
```

> NEW: You can now put ```<updateMaxEvents>10</updateMaxEvents>```  in datasets.xml (in with the other settings near the top) to change the maximum number of file changes (default=10) that will be processed by the updateEveryNMillis system. A larger number (100?) may be useful when it is very important that the dataset be kept always up-to-date. See the [updateMaxEvents documentation](https://erddap.github.io/setupDatasetsXml.html#updateMaxEvents). Thanks to John Maurer.


There might be others too.

**Comment by srstsavage** [comment]
JAVA_OPT `-d64` was removed from axiom/docker-erddap here:

https://github.com/axiom-data-science/docker-erddap/pull/49/files

and is in place for the last two release tags (`axiom/docker-erddap:2.22-jdk17-openjdk` and `axiom/docker-erddap:2.23-jdk17-openjdk`).

`nGridThreads` and `nTableThreads` are unset in datasets.xml so they should get good defaults depending on dynamic detection of available cores:
https://github.com/ioos/erddap-gold-standard/blob/master/erddap/content/datasets.xml#L15-L16

**Review by srstsavage — APPROVED** [review]

**Comment by srstsavage** [comment]
@callumrollo [GenerateDatasetsXml.sh](https://github.com/ioos/erddap-gold-standard/blob/master/GenerateDatasetsXml.sh#L5) also references a specific version of `axiom/docker-erddap` which needs to be updated to `2.23-jdk17-openjdk` or `latest`

**Comment by callumrollo** [comment]
I think this is ready for merge @MathewBiddle unless there's more to add?

It would make to sense to merge it at the same time as #49 though to that the docs are aligned with the files

**Comment by MathewBiddle** [comment]
Looks great! Thanks for the effort! Merged $49 too.

**Pull request merged**
